version: '3'
services:
  api:
    image: idealpostcodes/postcodes.io:latest
    container_name: api
    depends_on:
      - db
    environment:
      - POSTGRES_DB=postcodesiodb
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postcodesio
      - POSTGRES_HOST=db
    ports:
      - 8000:8000
  db:
    image: idealpostcodes/postcodes.io.db:latest
    container_name: db
    environment:
      - POSTGRES_DB=postcodesiodb
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postcodesio